stages:
  - dockerize
  - build
  - test

build_api:
  stage: build
  services:
    - name: docker:dind
      entrypoint: ["env", "-u", "DOCKER_HOST"]
      command: ["dockerd-entrypoint.sh"]
  variables:
    DOCKER_DRIVER: overlay2
  before_script:
    - docker version
    - docker-compose version
  script:
    - echo "building the solution..."
    - docker-compose up --build
  tags:
    - "recette"